disabled-worlds:
  - world_nopvp

enable-cooldown: 4
disable-cooldown: 4

lang:
  pvp-enabled: '&e❤ &6HubPvP+ has been &aActivated&7!'
  pvp-enabling: '&e❤ &6HubPVP+ will activate in &e%time%&7.'
  pvp-disabled: '&e❤ &6HubPVP+ Mode has been &cDeactivated&7!'
  pvp-disabling: '&e❤ &6HubPVP+ will deactivate, in &e%time%&7.'
  reloaded: '&aSuccessfully HubPvP+ config reloaded!'
  disabled-in-world: "&cYou may not use this in this world!"
  broadcast_msg: "&6[💀] &e%victim%"
