
  # List of worlds where PvP is disabled
disabled-worlds:
  - world_nopvp

# Cooldown duration (in seconds) for enabling PvP
enable-cooldown: 4

# Cooldown duration (in seconds) for disabling PvP
disable-cooldown: 4

# Flag to enable or disable sound effects for PvP actions
sound-effects: true

# Language settings for various PvP-related messages
lang:
  # Message displayed when PvP is enabled
  pvp-enabled: '&e❤ &6HubPvP+ has been &aActivated&7!'

  # Message displayed while PvP is enabling with a countdown timer
  pvp-enabling: '&e❤ &6HubPVP+ will activate in &e%time%&7.'

  # Message displayed when PvP is disabled
  pvp-disabled: '&e❤ &6HubPVP+ Mode has been &cDeactivated&7!'

  # Message displayed while PvP is disabling with a countdown timer
  pvp-disabling: '&e❤ &6HubPVP+ will deactivate, in &e%time%&7.'

  # Message displayed when the configuration is successfully reloaded
  reloaded: '&aSuccessfully HubPvP+ config reloaded!'

  # Message displayed when a player tries to use a feature in a disabled world
  disabled-in-world: "&cYou may not use this in this world!"

  # Broadcast message template for a PvP victim
  broadcast_msg: "&6[💀] &e%victim%"